import os
import cv2
import numpy as np
image = cv2.imread("C:/Users/pooja/Desktop/OpenCV/apple.png", cv2.IMREAD_COLOR)
cv2.imshow("window", image)
cv2.waitKey(0)
image = cv2.imread("C:/Users/pooja/Desktop/OpenCV/apple.png", cv2.IMREAD_GRAYSCALE)
cv2.imshow("window", image)
cv2.waitKey(0)
image = cv2.imread("C:/Users/pooja/Desktop/OpenCV/apple.png", 1)
cv2.imshow("window", image)
cv2.waitKey(0)
store_path = r"C:\Users\pooja\Desktop\OpenCV\images"
os.chdir(store_path)
cv2.imwrite("image.png", image)
blue_sat, red_sat, green_sat = cv2.split(image)
cv2.imshow("blue_saturation", blue_sat)
cv2.waitKey(0)
cv2.imshow("red_saturation", red_sat)
cv2.waitKey(0)
cv2.imshow("green_saturation", green_sat)
cv2.waitKey(0)
resized_image = cv2.resize(image, (200,200))
cv2.imshow("resized apple", resized_image)
cv2.waitKey(0)
flower = cv2.imread("C:/Users/pooja/Desktop/OpenCV/flower.png", 1)
cv2.imshow("flower", flower)
cv2.waitKey(0)
resized_flower = cv2.resize(flower, (1000, 1080))
second_image = cv2.addWeighted(image, 0.8, resized_flower, 0.5, 0)
cv2.imshow("window", second_image)
cv2.waitKey(0)
third_image = cv2.subtract(image, resized_flower)
cv2.imshow("subtracted image", third_image)
cv2.waitKey(0)
krnel = np.ones((7,7), np.uint8)
eroded_image = cv2.erode(flower, krnel) 
cv2.imshow("eroded flower", eroded_image)
cv2.waitKey(0)
g_blurred_image = cv2.GaussianBlur(flower, (99,99), 0)
cv2.imshow("gaussian blurred image", g_blurred_image)
cv2.waitKey(0)
m_blurred_image = cv2.medianBlur(flower, (5))
cv2.imshow("median blurred image", m_blurred_image)
cv2.waitKey(0)
cv2.destroyAllWindows()