import os
import cv2
import numpy as np
image = cv2.imread("C:/Users/pooja/Desktop/OpenCV/apple.png", cv2.IMREAD_COLOR)
cv2.imshow("window", image)
cv2.waitKey(0)
image = cv2.imread("C:/Users/pooja/Desktop/OpenCV/apple.png", cv2.IMREAD_GRAYSCALE)
cv2.imshow("window", image)
cv2.waitKey(0)
image = cv2.imread("C:/Users/pooja/Desktop/OpenCV/apple.png", 1)
cv2.imshow("window", image)
cv2.waitKey(0)
store_path = r"C:\Users\pooja\Desktop\OpenCV\images"
os.chdir(store_path)
cv2.imwrite("image.png", image)
blue_sat, red_sat, green_sat = cv2.split(image)
cv2.imshow("blue_saturation", blue_sat)
cv2.waitKey(0)
cv2.imshow("red_saturation", red_sat)
cv2.waitKey(0)
cv2.imshow("green_saturation", green_sat)
cv2.waitKey(0)
resized_image = cv2.resize(image, (200,200))
cv2.imshow("resized apple", resized_image)
cv2.waitKey(0)
flower = cv2.imread("C:/Users/pooja/Desktop/OpenCV/flower.png", 1)
cv2.imshow("flower", flower)
cv2.waitKey(0)
resized_flower = cv2.resize(flower, (1000, 1080))
second_image = cv2.addWeighted(image, 0.8, resized_flower, 0.5, 0)
cv2.imshow("window", second_image)
cv2.waitKey(0)
third_image = cv2.subtract(image, resized_flower)
cv2.imshow("subtracted image", third_image)
cv2.waitKey(0)
krnel = np.ones((7,7), np.uint8)
eroded_image = cv2.erode(flower, krnel) 
cv2.imshow("eroded flower", eroded_image)
cv2.waitKey(0)
g_blurred_image = cv2.GaussianBlur(flower, (99,99), 0)
cv2.imshow("gaussian blurred image", g_blurred_image)
cv2.waitKey(0)
m_blurred_image = cv2.medianBlur(flower, (5))
cv2.imshow("median blurred image", m_blurred_image)
cv2.waitKey(0)
b_blurred_image = cv2.bilateralFilter(flower, 9, sigmaColor=50, sigmaSpace=50)
cv2.imshow("bilateral blur", b_blurred_image)
cv2.waitKey(0)
border = cv2.copyMakeBorder(flower, 15, 15, 15, 15, cv2.BORDER_CONSTANT, value=168)
cv2.imshow("bordered image", border)
cv2.waitKey(0)
reflection_border = cv2.copyMakeBorder(flower, 150, 150,150, 150, cv2.BORDER_REFLECT)
cv2.imshow("reflection border", reflection_border)
cv2.waitKey(0)
colour_to_greyscale = cv2.cvtColor(flower, cv2.COLOR_BGR2GRAY)
cv2.imshow("colour to greyscale", colour_to_greyscale)
cv2.waitKey(0)
inverted_image = 255-flower
cv2.imshow("inverted", inverted_image)
cv2.waitKey(0)
print(image.shape)
rows = image.shape[0]
columns = image.shape[1]
print(rows)
print(columns)
flower2 = image
for i in range(rows):
    for r in range(columns):
        flower2[i,r]=sum(flower2[i, r]) * 0.01
cv2.imshow("greyscale averaging", flower2)
cv2.waitKey(0)

cv2.destroyAllWindows()