import os
import cv2
image = cv2.imread("C:/Users/pooja/Desktop/OpenCV/apple.png", cv2.IMREAD_COLOR)
cv2.imshow("window", image)
cv2.waitKey(0)
image = cv2.imread("C:/Users/pooja/Desktop/OpenCV/apple.png", cv2.IMREAD_GRAYSCALE)
cv2.imshow("window", image)
cv2.waitKey(0)
image = cv2.imread("C:/Users/pooja/Desktop/OpenCV/apple.png", 1)
cv2.imshow("window", image)
cv2.waitKey(0)
store_path = r"C:\Users\pooja\Desktop\OpenCV\images"
os.chdir(store_path)
cv2.imwrite("image.png", image)
blue_sat, red_sat, green_sat = cv2.split(image)
cv2.imshow("blue_saturation", blue_sat)
cv2.waitKey(0)
cv2.imshow("red_saturation", red_sat)
cv2.waitKey(0)
cv2.imshow("green_saturation", green_sat)
cv2.waitKey(0)
resized_image = cv2.resize(image, (200,200))
cv2.imshow("resized apple", resized_image)
cv2.waitKey(0)
banana = cv2.imread(r"C:\Users\pooja\Desktop\OpenCV\banana.png", 1)
resized_banana = cv2.resize(banana, (1000, 1080))
#second_image = cv2.addWeighted(image + resized_banana)
cv2.destroyAllWindows()